CREATE TABLE CLOG_POST (
    POST_ID CHAR(36) NOT NULL,
    SITE_ID VARCHAR2(255),
    TITLE VARCHAR2(255) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_DATE DATE NOT NULL,
    MODIFIED_DATE DATE,
    CREATOR_ID VARCHAR2(255) NOT NULL,
    KEYWORDS VARCHAR2(255),
    ALLOW_COMMENTS NUMBER(10 ,0),
    VISIBILITY VARCHAR2(16) NOT NULL,
    CONSTRAINT clog_post_pk PRIMARY KEY(POST_ID)
);

CREATE TABLE CLOG_AUTOSAVED_POST (
    POST_ID CHAR(36) NOT NULL,
    SITE_ID VARCHAR2(255),
    TITLE VARCHAR2(255) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_DATE DATE NOT NULL,
    MODIFIED_DATE DATE,
    CREATOR_ID VARCHAR2(255) NOT NULL,
    KEYWORDS VARCHAR2(255),
    ALLOW_COMMENTS NUMBER(10 ,0),
    VISIBILITY VARCHAR2(16) NOT NULL,
    CONSTRAINT clog_autosaved_post_pk PRIMARY KEY(POST_ID)
);

CREATE TABLE CLOG_COMMENT (
    COMMENT_ID CHAR(36) NOT NULL,
    POST_ID CHAR(36) NOT NULL,
    SITE_ID VARCHAR2(255) NOT NULL,
    CREATOR_ID CHAR(36) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    MODIFIED_DATE DATE NOT NULL,
    CONTENT CLOB NOT NULL,
    CONSTRAINT clog_comment_pk PRIMARY KEY (COMMENT_ID)
);

CREATE TABLE CLOG_AUTHOR (
    USER_ID CHAR(36) NOT NULL,
    SITE_ID VARCHAR2(255) NOT NULL,
    TOTAL_POSTS NUMBER(10 ,0) NOT NULL,
    LAST_POST_DATE DATE,
    TOTAL_COMMENTS NUMBER(10 ,0) NOT NULL,
    CONSTRAINT clog_author_pk PRIMARY KEY (USER_ID,SITE_ID)
);

CREATE TABLE CLOG_PREFERENCES (
    USER_ID VARCHAR2 (36) NOT NULL, 
    SITE_ID VARCHAR2 (255) NOT NULL, 
    EMAIL_FREQUENCY VARCHAR2(32) NOT NULL,
    CONSTRAINT clog_preferences_pk PRIMARY KEY (USER_ID,SITE_ID)
);

CREATE TABLE CLOG_GLOBAL_PREFERENCES (
    USER_ID VARCHAR2(36) NOT NULL, 
    SHOW_BODY NUMBER(3, 0) NOT NULL DEFAULT '1',
    CONSTRAINT clog_global_preferences_pk PRIMARY KEY (USER_ID)
);
